# Generated by Django 4.1.7 on 2023-04-04 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyMp3Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None title', max_length=50)),
                ('mp3_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'ogg'])])),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp3webplayer.singer')),
            ],
        ),
    ]
