# Generated by Django 4.1.7 on 2023-04-04 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mp3webplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3webplayer', '0002_mymp3player_playlist_alter_mymp3player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymp3player',
            name='mp3_file',
            field=models.FileField(upload_to=mp3webplayer.models.upload, validators=[django.core.validators.FileExtensionValidator(['mp3', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='mymp3player',
            name='photo',
            field=models.ImageField(upload_to=mp3webplayer.models.upload),
        ),
        migrations.AlterField(
            model_name='mymp3player',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_set', to='mp3webplayer.singer'),
        ),
    ]
