# Generated by Django 4.1.7 on 2023-04-05 04:48

import django.core.validators
from django.db import migrations, models
import mp3webplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3webplayer', '0003_alter_mymp3player_mp3_file_alter_mymp3player_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymp3player',
            options={'ordering': ('playlist',)},
        ),
        migrations.AlterField(
            model_name='mymp3player',
            name='mp3_file',
            field=models.FileField(max_length=1000, upload_to=mp3webplayer.models.upload, validators=[django.core.validators.FileExtensionValidator(['mp3', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='mymp3player',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to=mp3webplayer.models.upload),
        ),
    ]
